import { Linking, Pressable, StyleSheet, Text, View } from 'react-native';
import { SchemeMatch } from '@/hooks/use-scheme-search';
import { AccessColors, AccessRadius, AccessSpacing, AccessFontSize, AccessFontWeight } from '@/constants/access-theme';

export function SchemeResultsPanel({ results, loading, error }: { results: SchemeMatch[]; loading: boolean; error: string | null }) {
  if (loading) return <Text style={styles.note}>Finding potential support…</Text>;
  if (error) return <Text style={styles.error}>{error}</Text>;
  if (!results.length) return null;
  return <View style={styles.wrap}><Text style={styles.title}>Potential Support Available</Text><Text style={styles.note}>Verify eligibility and requirements on the official source.</Text>{results.map((scheme) => <View key={scheme.id} style={styles.card}><Text style={styles.badge}>{scheme.category}</Text><Text style={styles.name}>{scheme.name}</Text><Text style={styles.body}>{scheme.description}</Text><Text style={styles.body}><Text style={styles.label}>Benefit: </Text>{scheme.benefits}</Text><Text style={styles.note}>Documents: {scheme.documents_required?.join(', ') || 'Check official requirements'}</Text><Pressable onPress={() => Linking.openURL(scheme.source_url)} accessibilityRole="link" style={styles.link}><Text style={styles.linkText}>View official requirements →</Text></Pressable></View>)}</View>;
}
const styles = StyleSheet.create({wrap:{gap:AccessSpacing.md},title:{fontSize:AccessFontSize.lg,fontWeight:AccessFontWeight.bold,color:AccessColors.navy},card:{backgroundColor:AccessColors.cardDefault,borderWidth:1,borderColor:AccessColors.border,borderRadius:AccessRadius.md,padding:AccessSpacing.md,gap:AccessSpacing.sm},badge:{alignSelf:'flex-start',backgroundColor:AccessColors.tealFaint,color:AccessColors.tealDark,paddingHorizontal:AccessSpacing.sm,paddingVertical:4,borderRadius:AccessRadius.full,fontSize:AccessFontSize.xs,fontWeight:AccessFontWeight.bold},name:{fontSize:AccessFontSize.md,fontWeight:AccessFontWeight.semibold,color:AccessColors.textPrimary},body:{fontSize:AccessFontSize.sm,color:AccessColors.textSecondary},label:{fontWeight:AccessFontWeight.bold},note:{fontSize:AccessFontSize.sm,color:AccessColors.textSecondary},error:{fontSize:AccessFontSize.sm,color:'#B91C1C'},link:{alignSelf:'flex-start',paddingVertical:AccessSpacing.xs},linkText:{color:AccessColors.tealDark,fontWeight:AccessFontWeight.semibold}});
